# Generated by Django 5.2.3 on 2025-06-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Esporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lesao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "parte_afetada",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "intensidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Baixa", "Baixa"),
                            ("Média", "Média"),
                            ("Alta", "Alta"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tempo_medio_recuperacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Causa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("Amador", "Amador"),
                            ("Profissional", "Profissional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("causa", models.TextField()),
                (
                    "esporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tema.esporte"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LesaoEsporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "esporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tema.esporte"
                    ),
                ),
                (
                    "lesao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tema.lesao"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrevencaoTratamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Prevenção", "Prevenção"),
                            ("Tratamento", "Tratamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "lesao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuidados",
                        to="tema.lesao",
                    ),
                ),
            ],
        ),
    ]
